---
title: "Academic"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[Academic CV](pdfs/cv-academic-Rohan_Alexander.pdf)

### Education

#### Australian National University

* Ph.D. Economics (2015--2019)  
My research focused on Australian political and economic history, such as exploring: the impact of various events on discussion in federal parliaments; who voted for Federation; and which politicians get an incumbency effect.  
Panel: [John Tang](https://sites.google.com/site/jptang/) (primary supervisor), [Martine Mariotti](https://www.cbe.anu.edu.au/about/staff-directory/?profile=Martine-Mariotti) (chair), [Zach Ward](https://sites.google.com/site/zachaward/) and [Tim Hatton](https://sites.google.com/site/timhattonwebsite/).  
Thesis: Essays on Applied Historical Labour Economics.  
Status: The award of my degree has been approved, however it will only be conferred at the next graduation ceremony, which is scheduled for December 2019.
* M.Economics (2012)

#### University of Queensland

* B.Economics (Hons) (2004-2008)  
I wrote an honours thesis in game theory supervised by [Rabee Tourky](http://tourky.org/) and was a research assistant to: [Flavio Menezes](https://economics.uq.edu.au/profile/2324/flavio-menezes) on a project about ACCC decisions; and [Liam Wagner](http://www.liamwagner.com/) on a project about energy prices.

### Published papers
* Rohan Alexander and Zach Ward, 2018, '[Age at Arrival and Assimilation During the Age of Mass Migration](https://www.cambridge.org/core/journals/journal-of-economic-history/article/age-at-arrival-and-assimilation-during-the-age-of-mass-migration/85FDB674232C30BDD889711D343F22FE)', *The Journal of Economic History*, 78(3), 904-937.  
[Working paper version](pdfs/2018_02_21-Age_at_arrival.pdf).

### Working papers
* [Monica Alexander](monicaalexander.com) and Rohan Alexander, '[The Effect of Elections and Prime Ministers on Discussion in the Australian Federal Parliament (1901—2018)](pdfs/AlexanderAlexander-EffectofElectionsandPrimeMinisters.pdf)'.  
* Rohan Alexander and Tim Hatton, 'The Making of a Nation: Who Voted for Australian Federation?'.
* Rohan Alexander and Patrick Leslie, 'The Effect of State on Senators’ Speeches in the Australian Federal Parliament (1901–2018)'
* Rohan Alexander, Patrick Dumond, Lauren Kennedy, and Patrick Leslie, ‘Forecasting Parliamentary Elections’.

### Presentations
* Forecasting Parliamentary Elections  
 *Upcoming* 10 December 2019, Monash University, Department of Econometrics & Business Statistics, Melbourne.  
 [9 December 2019](pdfs/2019-12-09-slides-ASQPS.pdf), Australian Society for Quantitative Political Science Conference, Melbourne.  
 2 December 2019, Australian National University, Cake for Comments, Canberra.  
 [20 November 2019](pdfs/2019-11-20-slides-POP.pdf), POP Politics Workshop, Canberra.
 17 October 2018, University of Toronto, Political Behaviour Group, Toronto.
* A Word-Count Based Classifier of Politicians in the Australian Federal Parliament (1901--2018)  
 *Upcoming* 21 November 2019, SoDa Labs, Monash University, Melbourne.  
 [4 September 2019](pdfs/2019-09-04-slides-Wroclow.pdf), European Consortium for Political Research, General Conference, Wroclaw.  
 [22 June 2019](pdfs/2019-06-22-slides-Belfast-EPSA.pdf), European Political Science Association, Annual Conference, Belfast.  
 [18 June 2019](pdfs/2019-06-18-slides-QTADublin.pdf), Quantitative Text Analysis Workshop, Dublin.
*  The Effect of Elections and Prime Ministers on Discussion in the Australian Federal Parliament (1901—2018)  
 [11 January 2019](pdfs/2019-01-11-slides-warwick.pdf), Political Methodology Specialist Group, Annual Conference, Warwick.  
 [11 December 2018](pdfs/2018-12-12-slides-rostock.pdf), Max Planck Institute for Demographic Research, Rostock.  
 [22 November 2018](pdfs/2018-11-22-slides-UofT.pdf), University of Toronto, Political Behaviour Group, Toronto.  
 [25 October 2018](pdfs/2018-10-25-slides-RSE.pdf), Australian National University, Research School of Economics, Canberra..  
 [25 October 2018](pdfs/2018-10-25-slides-parlimentarylibrary.pdf), Parliamentary Library, Parliament of Australia, Canberra.  
 [24 October 2018](pdfs/2018-10-24-slides-SPIR.pdf), Australian National University, School of Politics and International Relations, Canberra. 
* Exploring Australia's Hansard (1901--2017)  
 (Poster) 7-9 September, 2018 Economic History Association Meeting, Montreal.
* A Surnames-Based Analysis of Tasmanian Social Mobility (1803--2015)  
 20 May 2016, UC Berkeley, Economic History Lunch, Berkeley.  
 2 May 2016, Australian National University, Research School of Economics, Canberra.



### Teaching Experience
#### Australian National University
* Tutor, Macroeconomics 3, Semester 2, 2017, [evaluations](pdfs/2018-02-05-Sem_2_2017-ECON3102_-_Macroeconomics_3.pdf) 
* Tutor, Microeconomics 3, Semester 1, 2017, [evaluations](pdfs/2018-02-05-Sem_1_2017-ECON3101_-_Microeconomics_3.pdf) 
* Tutor, Behavioural Economics, Semester 2, 2015, [evaluations](pdfs/2018-02-05-Sem_2_2015-ECON2013_Behavioural_Economics.pdf) 
* Tutor, Business Economics, Semester 1, 2015, [evaluations](pdfs/2018-02-05-Sem_1_2015-ECON8069_Business_Economics.pdf) 
* Tutor, Microeconomics 1, Semester 1, 2013, [evaluations](pdfs/2018-02-05-Sem_1_2013-ECON1101_Microeconomics_1.pdf) 
* Tutor, Foundations of Economic and Financial Models, Semester 2, 2012

#### University of Queensland
* Tutor, Microeconomic Policy, Semester 2, 2008
* Tutor, Microeconomic Theory, Semester 1, 2008
* Tutor, Introductory Microeconomics, Semester 2, 2007
* Tutor, Introductory Microeconomics, Semester 1, 2007
