---
title: "Home"
site: radix::radix_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Radix at:
# https://rstudio.github.io/radix/website.html

```

Hi, I’m Rohan Alexander.

I submitted my PhD thesis in Economics at the Australian National University in Canberra in February 2019 and expect to graduate in July 2019. My thesis looks at various topics in applied historical labour economics, including migrant outcomes, voting patterns, and social mobility, all making use of historical data sources that I constructed. For instance, in a paper published in The Journal of Economic History, I examined the effect of how old a child migrant was when they arrived in the US on various outcomes when they were an adult. This analysis was performed on a linked historical dataset of Ellis Island arrivals and the 1940 US Census, comparing differences between brothers. You can see more about my academic interests [here](https://rohanalexander.com/academic.html).

In general, my research explores economic and political history using quantitative methods. A large part of my research involves first constructing my datasets, either though optical character recognition (OCR) or web-scraping, and then cleaning and preparing them in a reproducible way. For example, I digitized and cleaned the entire record of what was said in the Australian Parliament House from 1901 through to 2018, corresponding to around 15,000 days and almost a billion words. Recently my research uses analysis methods such as: text analysis using topic models and multinomial regression; Bayesian models in the context of multilevel regression and poststratification (MRP); and logistic regression in the context of historical voting.

I have tutored (equivalent to TA) macroeconomics and microeconomics courses at many different undergraduate levels and have tutored behavioural economics and quantitative methods at a second year undergraduate level. I enjoy teaching at the intersection of economics and quantitative social science more broadly.

Professionally, until recently I worked on a casual basis as a consultant at Grosvenor Public Sector Advisory on public-sector procurement data. I've previously worked at the Reserve Bank of Australia, the Centre for International Economics, and at GoCampaign, which was a business that I started with some friends. You can see more about my professional experience [here](https://rohanalexander.com/professional.html).

At the moment my side-projects are Petit Poll and No Pour Choices. Petit Poll combines non-representative polling data that we gather ourselves with a hierarchical Bayesian model to cheaply deliver meaningful Australian political polling. No Pour Choices is an iOS app for organising a wine collection.

Finally, I probably spend too much money on books, and certainly too much time at libraries. You can see some of the books that I recommend [here](https://rohanalexander.com/bookshelf.html). If you have any book recommendations of your own, I've love to hear them.